/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const autogenerated = (dirName) => ({type: 'autogenerated', dirName});

const category = (label, items) => ({
  type: 'category',
  label,
  items,
});

const dirCategory = (label, dirName) => category(label, [autogenerated(dirName)]);

const linkedCategory = (label, id, items) => ({
  type: 'category',
  label,
  link: {type: 'doc', id},
  items,
});

const sidebars = {
  knowledgeSidebar: [
    'intro',
    linkedCategory('Java 基础', 'java-foundation/index', [
      'java-foundation/jvm-memory-model',
      'java-foundation/concurrency-roadmap',
      dirCategory('并发编程', 'java-foundation/concurrency'),
      dirCategory('JVM', 'java-foundation/jvm'),
      dirCategory('Java 语言与集合', 'java-foundation/language'),
    ]),
    linkedCategory('Spring 与微服务', 'spring-cloud/index', [
      'spring-cloud/service-governance',
      dirCategory('Spring', 'spring-cloud/spring'),
      dirCategory('Spring Boot', 'spring-cloud/spring-boot'),
      dirCategory('Spring Cloud', 'spring-cloud/spring-cloud'),
    ]),
    linkedCategory('MySQL', 'mysql/index', [
      'mysql/slow-sql-diagnosis',
      category('基础与执行流程', [
        'mysql/基础笔记/基本指令',
        'mysql/基础笔记/一条sql查询语句的执行',
      ]),
      category('索引与存储引擎', [
        'mysql/基础笔记/Mysql索引',
        'mysql/基础笔记/Mysql字段宽度与索引',
        'mysql/基础笔记/MyISAM和InnoDB的区别',
      ]),
      category('事务与 MVCC', ['mysql/基础笔记/如何理解MVCC中的ReadView']),
      category('性能与面试', [
        'mysql/基础笔记/高性能mysql-第六章',
        'mysql/基础笔记/Mysql面试重点看',
      ]),
    ]),
    linkedCategory('Redis', 'redis/index', [
      'redis/cache-consistency',
      category('入门与安装', [
        'redis/基础笔记/Redis linux 安装',
        'redis/基础笔记/Redis产生的由来',
        'redis/基础笔记/Redis使用场景',
      ]),
      category('数据结构与数据类型', [
        'redis/基础笔记/Redis数据结构',
        'redis/基础笔记/Redis数据类型',
      ]),
      category('核心原理', [
        'redis/基础笔记/Redis为什么快？',
        'redis/基础笔记/Redis的多路复用',
        'redis/基础笔记/Redis缓存淘汰策略',
      ]),
      category('对比与面试', [
        'redis/基础笔记/memcache和redis的区别',
        'redis/基础笔记/Redis面试必看',
        'redis/基础笔记/Redis补充',
      ]),
    ]),
    linkedCategory('RocketMQ', 'rocketmq/index', ['rocketmq/transaction-message']),
    linkedCategory('分布式', 'distributed/index', ['distributed/consistency-patterns']),
    linkedCategory('线上排查', 'troubleshooting/index', [
      'troubleshooting/full-gc-troubleshooting',
      'troubleshooting/oom-cpu100',
    ]),
    linkedCategory('架构设计', 'architecture/index', [
      'architecture/design-methodology',
      dirCategory('设计原则', 'architecture/design-patterns/设计原则'),
      dirCategory('设计模式', 'architecture/design-patterns/设计模式'),
      dirCategory('系统设计', 'architecture/system-design'),
    ]),
    linkedCategory('后端框架与中间件', 'backend-frameworks/index', [
      dirCategory('MyBatis', 'backend-frameworks/mybatis'),
      dirCategory('Netty', 'backend-frameworks/netty'),
      dirCategory('Sentinel', 'backend-frameworks/sentinel'),
    ]),
    linkedCategory('业务系统设计', 'business-systems/index', [
      dirCategory('认证鉴权', 'business-systems/auth'),
      dirCategory('支付系统', 'business-systems/payment'),
    ]),
    linkedCategory('计算机基础', 'computer-foundation/index', [
      dirCategory('汇编语言', 'computer-foundation/assembly'),
      category('计算机网络', [
        'computer-foundation/network/计算机网络协议',
        dirCategory('趣谈网络协议', 'computer-foundation/network/趣谈网络协议'),
      ]),
      dirCategory('操作系统', 'computer-foundation/os'),
    ]),
    linkedCategory('数据结构与算法', 'algorithm/index', [
      dirCategory('2021 基础专题', 'algorithm/2021年'),
      dirCategory('算法课程笔记', 'algorithm/个人/wangzheng4'),
      dirCategory('刷题总结', 'algorithm/刷题总结'),
      dirCategory('学习方法与模板', 'algorithm/学习总结'),
    ]),
    linkedCategory('面试复盘', 'interview/index', [
      dirCategory('面经与场景题', 'interview/面经与场景题'),
    ]),
    linkedCategory('技术输出', 'output/index', [autogenerated('output')]),
    linkedCategory('开发工具与环境', 'dev-tools/index', [
      dirCategory('通用工具', 'dev-tools/general'),
      dirCategory('Git', 'dev-tools/git'),
      category('Linux', [
        'dev-tools/linux/Linux查找日志操作命令',
        'dev-tools/linux/vi vim基本使用方法 - iTech - 博客园',
        dirCategory('Linux 基础操作', 'dev-tools/linux/linux操作'),
        dirCategory('虚拟机安装', 'dev-tools/linux/虚拟机下linux安装'),
      ]),
      dirCategory('Maven', 'dev-tools/maven'),
      dirCategory('系统排查', 'dev-tools/system-troubleshooting'),
    ]),
    linkedCategory('AI 学习', 'ai-learning/index', [
      'ai-learning/入门课程/咕泡大模型入门课',
    ]),
    linkedCategory('扩展与历史归档', 'archive/index', [
      category('博客搭建', [
        dirCategory('Hexo', 'archive/blog-building/hexo'),
        dirCategory('Hugo', 'archive/blog-building/hugo'),
      ]),
      dirCategory('Python', 'archive/python'),
      dirCategory('资料与随笔', 'archive/misc'),
    ]),
  ],
};

module.exports = sidebars;
