/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  knowledgeSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Java 基础',
      link: {type: 'doc', id: 'java-foundation/index'},
      items: [
        'java-foundation/jvm-memory-model',
        'java-foundation/concurrency-roadmap',
        {type: 'category', label: '历史笔记', items: [{type: 'autogenerated', dirName: 'java-foundation/legacy'}]},
      ],
    },
    {
      type: 'category',
      label: 'Spring 与微服务',
      link: {type: 'doc', id: 'spring-cloud/index'},
      items: [
        'spring-cloud/service-governance',
        {type: 'category', label: '历史笔记', items: [{type: 'autogenerated', dirName: 'spring-cloud/legacy'}]},
      ],
    },
    {
      type: 'category',
      label: 'MySQL',
      link: {type: 'doc', id: 'mysql/index'},
      items: [
        'mysql/slow-sql-diagnosis',
        {type: 'category', label: '历史笔记', items: [{type: 'autogenerated', dirName: 'mysql/legacy'}]},
      ],
    },
    {
      type: 'category',
      label: 'Redis',
      link: {type: 'doc', id: 'redis/index'},
      items: [
        'redis/cache-consistency',
        {type: 'category', label: '历史笔记', items: [{type: 'autogenerated', dirName: 'redis/legacy'}]},
      ],
    },
    {
      type: 'category',
      label: 'RocketMQ',
      link: {type: 'doc', id: 'rocketmq/index'},
      items: ['rocketmq/transaction-message'],
    },
    {
      type: 'category',
      label: '分布式',
      link: {type: 'doc', id: 'distributed/index'},
      items: ['distributed/consistency-patterns'],
    },
    {
      type: 'category',
      label: '线上排查',
      link: {type: 'doc', id: 'troubleshooting/index'},
      items: [
        'troubleshooting/full-gc-troubleshooting',
        'troubleshooting/oom-cpu100',
      ],
    },
    {
      type: 'category',
      label: '架构设计',
      link: {type: 'doc', id: 'architecture/index'},
      items: [
        'architecture/design-methodology',
        {type: 'category', label: '设计模式', items: [{type: 'autogenerated', dirName: 'architecture/design-patterns'}]},
        {type: 'category', label: '系统设计', items: [{type: 'autogenerated', dirName: 'architecture/system-design'}]},
      ],
    },
    {
      type: 'category',
      label: '后端框架与中间件',
      link: {type: 'doc', id: 'backend-frameworks/index'},
      items: [{type: 'autogenerated', dirName: 'backend-frameworks'}],
    },
    {
      type: 'category',
      label: '业务系统设计',
      link: {type: 'doc', id: 'business-systems/index'},
      items: [{type: 'autogenerated', dirName: 'business-systems'}],
    },
    {
      type: 'category',
      label: '计算机基础',
      link: {type: 'doc', id: 'computer-foundation/index'},
      items: [{type: 'autogenerated', dirName: 'computer-foundation'}],
    },
    {
      type: 'category',
      label: '数据结构与算法',
      link: {type: 'doc', id: 'algorithm/index'},
      items: [{type: 'autogenerated', dirName: 'algorithm'}],
    },
    {
      type: 'category',
      label: '面试复盘',
      link: {type: 'doc', id: 'interview/index'},
      items: [{type: 'autogenerated', dirName: 'interview'}],
    },
    {
      type: 'category',
      label: '开发工具与环境',
      link: {type: 'doc', id: 'dev-tools/index'},
      items: [{type: 'autogenerated', dirName: 'dev-tools'}],
    },
    {
      type: 'category',
      label: 'AI 学习',
      link: {type: 'doc', id: 'ai-learning/index'},
      items: [{type: 'autogenerated', dirName: 'ai-learning'}],
    },
    {
      type: 'category',
      label: '扩展与历史归档',
      link: {type: 'doc', id: 'archive/index'},
      items: [{type: 'autogenerated', dirName: 'archive'}],
    },
  ],
};

module.exports = sidebars;
